baseURL = 'https://fahimfuad.github.io/'
title = "RIDHWAN"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = ""
googleAnalytics = "G-7FT5H63ZTX"

[markup.highlight]
style = "github-dark"

[params]
  author = "Ridhwan"
  info = "Elite Dumbass, that's about it"
  description = "Rid's site, where he gets a place and posts cringe"
  keywords = "blog, developer, personal"
  #avatarurl = "images/avatar.jpg"
  gravatar = "fahimfuad.dev@gmail.com"
  dateFormat = "02 Jan 2006"

  faviconSVG = "/static/favicon.svg"
  favicon_32 = "/static/favicon-32x32.png"
  favicon_16 = "/static/favicon-16x16.png"

  since = 2020

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/fahimfuad/"
  target = "_blank"
[[params.social]]
  name = "Facebook"
  icon = "fa fa-facebook fa-2x"
  weight = 2
  url = "https://www.facebook.com/rdxreductor/"
  target = "_blank"
[[params.social]]
  name = "Discord"
  icon = "fa fa-discord fa-2x"
  weight = 3
  url = "https://discord.com/users/776686994457362443/"
  target = "_blank"
[[params.social]]
  name = "Reddit"
  icon = "fa fa-reddit fa-2x"
  weight = 4
  url = "https://www.reddit.com/user/FahimFuad"
  target = "_blank"
[[params.social]]
  name = "Steam"
  icon = "fa fa-steam fa-2x"
  weight = 5
  url = "https://steamcommunity.com/id/Rid88/"
  target = "_blank"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 6
  url = "https://twitter.com/rdxreductor"
  target = "_blank"
[[params.social]]
  name = "Spotify"
  icon = "fa fa-spotify fa-2x"
  weight = 7
  url = "https://open.spotify.com/user/1qc5lti5spulomctjjmipuflz"
  target = "_blank"

# Menu links
[[menu.main]]
  name = "RidTweets"
  weight = 1
  url = "line/"
[[menu.main]]
  name = "RidPosts"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "RidWhat"
  weight = 3
  url = "about/"
[[menu.main]]
  name = "RidDiary"
  weight = 4
  url = "diary/"
